# Generated by Django 4.2 on 2024-10-10 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
    ]
